# 给你的自动化任务起个名字
name: Sync ttyd to Docker Hub

# 触发条件：
on:
  # 1. 允许你手动在 Actions 页面点击按钮触发
  workflow_dispatch:
  
  # 2. 定时任务：每个月的第一天凌晨3点自动运行一次 (用的是UTC时间)
  # 你可以修改这个 cron 表达式，或者不想要就删掉 schedule 这三行
  schedule:
    - cron: '0 3 1 * *'

# 具体的任务内容
jobs:
  build-and-push:
    # 在最新的 Ubuntu 系统上运行
    runs-on: ubuntu-latest
    
    # 任务步骤
    steps:
      # 第一步：登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 第二步：拉取、标记、并推送镜像
      - name: Pull, Tag, and Push
        run: |
          # 定义源镜像和目标镜像的名称
          SOURCE_IMAGE="ghcr.io/ttyd-project/ttyd:latest"
          TARGET_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/ttyd:latest"

          echo "Pulling latest image from ${SOURCE_IMAGE}"
          docker pull ${SOURCE_IMAGE}

          echo "Tagging image to ${TARGET_IMAGE}"
          docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}

          echo "Pushing image to Docker Hub"
          docker push ${TARGET_IMAGE}

          echo "Sync completed!"
