# 给你的自动化任务起个名字
name: Build and Sync My Terminal from Source

# 触发条件
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 1 * *'

# 具体的任务内容
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 第1步：下载 ttyd 1.7.4 版本的源代码
      - name: Check out ttyd source code
        uses: actions/checkout@v4
        with:
          repository: tsl0922/ttyd
          ref: '1.7.4'

      # 第2步：安装编译依赖环境
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libjson-c-dev libwebsockets-dev

      # 第3步：编译 ttyd 源代码
      - name: Compile ttyd
        run: |
          mkdir build && cd build
          cmake ..
          make

      # 第4步：准备 Dockerfile 需要的文件
      - name: Prepare files for Docker build
        run: |
          mkdir -p ./dist/amd64
          cp ./build/ttyd ./dist/amd64/

      # 第5步：设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 第6步：登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 第7步：构建并推送到新的仓库名
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 【最重要的修改在这里！】我们把 ttyd 改成了 my-terminal
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-terminal:latest,${{ secrets.DOCKERHUB_USERNAME }}/my-terminal:1.7.4
          platforms: linux/amd64

