# 给你的自动化任务起个名字
name: Sync ttyd to Docker Hub

# 触发条件
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 1 * *'

# 具体的任务内容
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 【新增的修复步骤】第一步：登录到 GitHub Container Registry (ghcr.io)
      # 这是为了能成功拉取源镜像
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 第二步：登录到 Docker Hub
      # 这是为了能成功推送到你的仓库
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 第三步：拉取、标记、并推送镜像
      - name: Pull, Tag, and Push
        run: |
          SOURCE_IMAGE="ghcr.io/ttyd-project/ttyd:latest"
          TARGET_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/ttyd:latest"

          echo "Pulling latest image from ${SOURCE_IMAGE}"
          docker pull ${SOURCE_IMAGE}

          echo "Tagging image to ${TARGET_IMAGE}"
          docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}

          echo "Pushing image to Docker Hub"
          docker push ${TARGET_IMAGE}

          echo "Sync completed!"

