# 给你的自动化任务起个名字
name: Sync ttyd to Docker Hub

# 触发条件
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 1 * *'

# 具体的任务内容
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 第一步：登录到 GitHub Container Registry (ghcr.io)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 第二步：登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 第三步：拉取、标记、并推送镜像
      - name: Pull, Tag, and Push
        run: |
          # 【最终、决定性的修正】使用带架构后缀的、真实存在的标签！
          SOURCE_IMAGE="ghcr.io/tsl0922/ttyd:1.7.4-amd64"

          # 我们把它标记成我们自己的 latest 标签
          TARGET_IMAGE_LATEST="${{ secrets.DOCKERHUB_USERNAME }}/ttyd:latest"

          echo "Pulling latest image from ${SOURCE_IMAGE}"
          docker pull ${SOURCE_IMAGE}
          
          echo "Tagging image to ${TARGET_IMAGE_LATEST}"
          docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE_LATEST}
          echo "Pushing latest image to Docker Hub"
          docker push ${TARGET_IMAGE_LATEST}

          echo "Sync completed!"

