# 给你的自动化任务起个名字
name: Build and Sync ttyd from Source

# 触发条件
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 1 * *'

# 具体的任务内容
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 第1步：下载 ttyd 1.7.4 版本的源代码
      - name: Check out ttyd source code
        uses: actions/checkout@v4
        with:
          repository: tsl0922/ttyd
          ref: '1.7.4'

      # 第2步：安装编译依赖环境 (我们之前在 README 里看到的)
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libjson-c-dev libwebsockets-dev

      # 第3步：编译 ttyd 源代码，生成可执行文件
      - name: Compile ttyd
        run: |
          mkdir build && cd build
          cmake ..
          make

      # 第4步：【关键步骤】创建 Dockerfile 需要的 dist 目录和文件
      - name: Prepare files for Docker build
        run: |
          mkdir -p ./dist/amd64
          cp ./build/ttyd ./dist/amd64/

      # 第5步：设置 Docker Buildx，这是一个增强的构建工具
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 第6步：登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 第7步：从我们准备好的文件构建 Docker 镜像，并直接推送到你的 Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ttyd:latest,${{ secrets.DOCKERHUB_USERNAME }}/ttyd:1.7.4
          # 我们明确告诉它，编译的是 amd64 架构
          platforms: linux/amd64
